# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkTYISyNb0aCRp7iLf5_-FNxocX0WdMY
"""



import math

print("=== CALCULADORA ===")
print("1 - Soma")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")
print("5 - Raiz Quadrada")
print("6 - Porcentagem")
opcao = input("Escolha:")

num1 = float(input("Digite o primeiro numero:"))
num2 = float(input("Digite o segundo numero:"))

if opcao == "1":
  resultado = num1 + num2
  print("Resultado:", resultado)

elif opcao == "2":
  resultado = num1 - num2
  print("Resultado:", resultado)

elif opcao == "3":
  resultado = num1 * num2
  print("Resultado:", resultado)

elif opcao == "4":
  resultado = num1/ num2
  print("Resultado:", resultado)

elif opcao == "5":
  resultado = math.sqrt(num1)
  print("Resultado:", resultado)

elif opcao == "6":
  resultado = (num1/100) * num2
  print("Resultado:", resultado)
else:
  print("Opção inválida!")