# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PU9ofIgQoXgy7tETqqLjth6BesSBVfYt
"""

produtos = []

def cadastrar():
    nome = input("Nome do produto: ")
    preco = float(input("Preço: R$ "))

    produto = {
        "nome": nome,
        "preco": preco
    }

    produtos.append(produto)
    print("\nProduto cadastrado com sucesso!\n")


def listar():
    if not produtos:
        print("\nNenhum produto cadastrado.\n")
        return

    print("\n===== PRODUTOS =====")

    for i, produto in enumerate(produtos):
        print(f"{i + 1} - {produto['nome']} | R$ {produto['preco']:.2f}")

    print()


def editar():
    listar()

    if not produtos:
        return

    while True:
        try:
            indice = int(input("Número do produto: ")) - 1
            if 0 <= indice < len(produtos):
                produtos[indice]["nome"] = input("Novo nome: ")
                produtos[indice]["preco"] = float(input("Novo preço: R$ "))
                print("\nProduto atualizado!\n")
                break
            else:
                print("\nProduto não encontrado. Por favor, insira um número válido.\n")
        except ValueError:
            print("\nEntrada inválida. Por favor, digite um número inteiro para o produto.\n")


def excluir():
    listar()

    if not produtos:
        return

    while True:
        try:
            indice = int(input("Número do produto: ")) - 1
            if 0 <= indice < len(produtos):
                removido = produtos.pop(indice)
                print(f"\n{removido['nome']} removido com sucesso!\n")
                break
            else:
                print("\nProduto não encontrado. Por favor, insira um número válido.\n")
        except ValueError:
            print("\nEntrada inválida. Por favor, digite um número inteiro para o produto.\n")


while True:

    print("====== MENU ======")
    print("1 - Cadastrar produto")
    print("2 - Listar produtos")
    print("3 - Editar produto")
    print("4 - Excluir produto")
    print("5 - Sair")

    opcao = input("Escolha: ")

    if opcao == "1":
        cadastrar()

    elif opcao == "2":
        listar()

    elif opcao == "3":
        editar()

    elif opcao == "4":
        excluir()

    elif opcao == "5":
        print("Sistema encerrado.")
        break

    else:
        print("\nOpção inválida!\n")